language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  include:
    - php: 7.1
      env: PHPSTAN=1

before_script:
    - composer install -n
    - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.7; fi

script:
    - vendor/bin/phpunit
    - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -c phpstan.neon -l 3 lib tests; fi

jobs:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
